### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by andretsc** [eltallerdetd/ArduinoYoutubeCounter#1]
Podras inserir como hacer rodar proyecto?

**Comment by eltallerdetd** [comment]
Buenas Andres, pronto creare el README. Toda la informacion esta en el video que hice para mi canal de Youtube. Saludos

Link al video mencionado: https://youtu.be/EmQhrd_vsR4

**Comment by arduinotux** [comment]
Buenas noches ,gracias
Saludos
